# Generated by Django 4.2.3 on 2023-07-23 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_alter_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='location',
            field=models.CharField(default='Unsure', max_length=100),
        ),
    ]
