# Generated by Django 4.2.3 on 2023-07-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_remove_expense_location_expense_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='deductible',
            field=models.BooleanField(default=False),
        ),
    ]
